name       : pychromecast
version    : 3.2.2
release    : 4
source     :
    - https://pypi.python.org/packages/source/P/PyChromecast/PyChromecast-3.2.2.tar.gz : da8a5a5a0d6c1046e818b586b247dd41f556ffa2a2e80f09cff6497c2db5879e
license    : MIT
component  : programming.python
summary    : Python module to talk to Google Chromecast
description: |
    Python module to talk to Google Chromecast.
rundeps    :
    - python-casttube
    - python-protobuf
    - python-six
    - python-zeroconf
build      : |
    %python3_setup
install    : |
    %python3_install
