name       : pychromecast
version    : 0.7.7
release    : 1
source     :
    - https://pypi.python.org/packages/cf/07/9a95c424e080f4b4e3b0b58cc91e67b03ce67e7f1a4f204e886d2838665f/PyChromecast-0.7.7.tar.gz : addc87ecb769c6883756081e0e775d6cac0b45b6698419d7419c589ff7f55244
license    : MIT
component  : programming.python
summary    : Python module to talk to Google Chromecast.
description: |
    Python module to talk to Google Chromecast.
builddeps  :
    - python-requests
    - python-setuptools
    - python-six
    - python-zeroconf
rundeps    :
    - python-protobuf
    - python-requests
    - python-six
    - python-zeroconf
build      : |  
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
