name       : pychromecast
version    : 0.8.0
release    : 2
source     :
    - https://pypi.python.org/packages/d7/17/db3f3cba3c592a95f8764656eca9ab7b75f32a66b75bf66a96022054f8a3/PyChromecast-0.8.0.tar.gz : 3edbc38bcef073e90a4a5a6c89872519a66a74017bc907320f2f893cb84bb261
license    : MIT
component  : programming.python
summary    : Python module to talk to Google Chromecast.
description: |
    Python module to talk to Google Chromecast.
builddeps  :
    - python-requests
    - python-setuptools
    - python-six
    - python-zeroconf
rundeps    :
    - python-protobuf
    - python-requests
    - python-six
    - python-zeroconf
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
